name: gradient_image
description: A new Flutter package project.
version: 0.1.0
author: Shun Kakinoki <shunkakinoki@gmail.com>
homepage: https://github.com/shunkakinoki/gradient_image

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
